[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.4    unsupported  03:40:04Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
opensearch                         active      3  opensearch                                 0  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
opensearch/0*                error     idle   0        10.88.155.155   9200/tcp  hook failed: "upgrade-charm"
opensearch/1                 error     idle   1        10.88.155.43    9200/tcp  hook failed: "upgrade-charm"
opensearch/2                 error     idle   2        10.88.155.218   9200/tcp  hook failed: "upgrade-charm"
self-signed-certificates/0*  active    idle   3        10.88.155.164             

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.88.155.155  juju-2eb443-0  ubuntu@22.04      Running
1        started  10.88.155.43   juju-2eb443-1  ubuntu@22.04      Running
2        started  10.88.155.218  juju-2eb443-2  ubuntu@22.04      Running
3        started  10.88.155.164  juju-2eb443-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 02:37:36 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 02:37:36 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-0: 02:37:36 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 02:37:38 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 02:37:38 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-1: 02:37:39 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 02:37:46 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 02:37:46 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 02:37:46 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 02:37:46 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 02:37:46 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-2: 02:37:47 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-opensearch-2: 02:40:28 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:29 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:40:30 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:40:30 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:31 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:31 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:40:32 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:32 ERROR unit.opensearch/0.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:40:33 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:40:33 ERROR unit.opensearch/0.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:40:34 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:34 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:40:35 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:35 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:36 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:37 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:40:37 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:37 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:40:37 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:40:37 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:40:38 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:40:38 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:38 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:40:38 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:38 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:40:38 ERROR unit.opensearch/0.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:40:38 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:40:39 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:39 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:40:39 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:40 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:40:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:40 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:40 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:40:40 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:40:40 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:40:40 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:40 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:40:41 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:41 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:40:41 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:40:41 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:43 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:40:43 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:40:43 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:44 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:44 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:40:45 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:40:48 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:48 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:40:52 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:52 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:40:56 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:40:56 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:40:59 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:00 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:02 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:41:02 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:03 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:41:03 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:03 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:41:07 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:07 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:41:11 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:11 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:41:14 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:14 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:15 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:17 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:18 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:20 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:20 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:20 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:20 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:21 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:21 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:21 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:21 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:21 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:21 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:22 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:22 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:22 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:22 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:22 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:22 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:23 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:23 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:23 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:23 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:23 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:23 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:24 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:24 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:24 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:41:24 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:24 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:41:25 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:41:25 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:25 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:41:25 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:41:25 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:25 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:41:26 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:41:26 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:26 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-0: 02:41:27 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:27 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:27 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:27 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:27 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:27 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:27 ERROR unit.opensearch/2.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:27 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:27 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:28 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:28 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:28 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:29 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:41:29 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:29 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:41:29 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:29 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:29 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:30 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:41:30 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:30 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:41:30 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:30 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:30 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:30 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:30 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:31 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:31 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:31 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:32 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:32 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:32 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:32 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:41:32 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:32 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:41:33 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:41:33 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:33 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:33 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:33 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:34 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:34 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:34 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:34 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:34 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:34 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:35 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:35 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:35 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:35 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:35 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:35 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:36 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:36 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:41:36 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:36 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:41:37 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:41:37 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:37 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:41:37 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:38 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:38 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:39 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:39 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:39 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:40 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:41:40 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:40 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:41:41 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:41:41 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:41 ERROR unit.opensearch/2.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:41:41 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:41:41 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:41 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:41:42 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:42 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:42 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:42 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:41:42 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:42 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:41:43 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:43 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:43 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:43 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:43 ERROR unit.opensearch/1.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:43 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:43 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:44 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:44 ERROR unit.opensearch/2.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:44 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:44 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:44 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:44 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:44 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:44 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:44 ERROR unit.opensearch/2.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:44 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:45 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:41:45 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:45 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:41:45 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:45 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:45 ERROR unit.opensearch/2.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:46 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:46 ERROR unit.opensearch/1.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:46 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:46 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:46 ERROR unit.opensearch/2.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:46 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:46 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:46 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:46 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:47 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:47 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:47 ERROR unit.opensearch/2.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:47 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:47 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:47 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:47 ERROR unit.opensearch/1.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:47 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:48 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:48 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:48 ERROR unit.opensearch/2.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:48 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:48 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:48 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:48 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:48 ERROR unit.opensearch/2.juju-log opensearch-peers:0: Request GET to https://10.88.155.155:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/.charm_node_lock/_source/0
unit-opensearch-0: 02:41:48 ERROR unit.opensearch/0.juju-log Request GET to https://10.88.155.155:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:41:49 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:49 ERROR unit.opensearch/1.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:49 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:49 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:49 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:49 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:49 ERROR unit.opensearch/1.juju-log opensearch-peers:0: Request GET to https://10.88.155.155:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/.charm_node_lock/_source/0
unit-opensearch-2: 02:41:49 ERROR unit.opensearch/2.juju-log opensearch-peers:0: Request GET to https://10.88.155.155:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/.charm_node_lock/_source/0
unit-opensearch-0: 02:41:50 ERROR unit.opensearch/0.juju-log Request GET to https://10.88.155.155:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:41:50 ERROR unit.opensearch/1.juju-log opensearch-peers:0: Request GET to https://10.88.155.155:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/.charm_node_lock/_source/0
unit-opensearch-2: 02:41:50 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:51 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:51 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:51 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:51 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:51 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:51 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:51 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:51 ERROR unit.opensearch/2.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:41:52 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:52 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:52 ERROR unit.opensearch/1.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:52 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:52 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:52 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:52 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:52 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:52 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:41:53 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:53 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:41:53 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:53 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:54 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:41:54 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:41:55 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:41:58 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:02 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:05 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:05 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:05 ERROR unit.opensearch/1.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:06 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:06 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:08 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:11 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:11 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:12 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:15 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:15 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:15 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:17 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:17 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:17 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:17 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:17 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:17 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:42:18 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:18 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:18 ERROR unit.opensearch/1.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:18 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:18 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:19 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:19 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:19 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:19 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:20 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:20 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:20 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:20 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:20 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:20 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:21 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:22 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:22 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:22 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:22 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:22 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:22 ERROR unit.opensearch/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:24 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:25 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:25 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:25 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:25 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:25 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:25 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:26 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:27 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:30 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:33 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:33 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:33 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:42:34 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:34 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:42:35 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:35 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:35 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:35 ERROR unit.opensearch/1.juju-log opensearch-peers:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:35 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:35 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:35 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:35 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:35 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:35 ERROR unit.opensearch/1.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:36 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:36 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:36 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-2: 02:42:37 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:37 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:37 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Request GET to https://10.88.155.218:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.88.155.218:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:42:38 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Request GET to https://10.88.155.218:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.88.155.218:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:42:39 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:39 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:39 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:39 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Request PUT to https://10.88.155.155:9200/.charm_node_lock?wait_for_active_shards=all with payload: {'settings': {'index': {'auto_expand_replicas': '0-all'}}} failed.(Attempts left: 2)
	Error: 400 Client Error: Bad Request for url: https://10.88.155.155:9200/.charm_node_lock?wait_for_active_shards=all
unit-opensearch-2: 02:42:39 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:40 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:40 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Request PUT to https://10.88.155.155:9200/.charm_node_lock?wait_for_active_shards=all with payload: {'settings': {'index': {'auto_expand_replicas': '0-all'}}} failed.(Attempts left: 1)
	Error: 400 Client Error: Bad Request for url: https://10.88.155.155:9200/.charm_node_lock?wait_for_active_shards=all
unit-opensearch-0: 02:42:40 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:40 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:41 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:41 ERROR unit.opensearch/2.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:41 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:42:41 ERROR unit.opensearch/0.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:41 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:42:42 ERROR unit.opensearch/0.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:42:42 ERROR unit.opensearch/0.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:42:42 ERROR unit.opensearch/0.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:42 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:42 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:42 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:42:43 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:43 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:43 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:43 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:43 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:43 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:44 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:45 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:49 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:42:51 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:52 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:42:55 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:55 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:59 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:43:00 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:02 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:06 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:09 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:43:10 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:43:10 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:43:11 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:43:12 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:43:12 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:12 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:43:12 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:43:13 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:43:13 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:43:13 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:43:13 ERROR unit.opensearch/0.juju-log opensearch-peers:0: [Errno 111] Connection refused
unit-opensearch-0: 02:43:15 ERROR unit.opensearch/0.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-0: 02:43:15 ERROR unit.opensearch/0.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-0: 02:43:15 ERROR unit.opensearch/0.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:15 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:43:15 ERROR unit.opensearch/0.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-0: 02:43:15 ERROR unit.opensearch/0.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:18 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:21 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:24 ERROR unit.opensearch/1.juju-log node-lock-fallback:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:42 ERROR unit.opensearch/0.juju-log Request GET to https://10.88.155.155:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 5)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/_snapshot/s3-repository
unit-opensearch-0: 02:44:43 ERROR unit.opensearch/0.juju-log Request GET to https://10.88.155.155:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 4)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/_snapshot/s3-repository
unit-opensearch-0: 02:44:44 ERROR unit.opensearch/0.juju-log Request GET to https://10.88.155.155:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 3)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/_snapshot/s3-repository
unit-opensearch-0: 02:44:45 ERROR unit.opensearch/0.juju-log Request GET to https://10.88.155.155:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/_snapshot/s3-repository
unit-opensearch-0: 02:44:46 ERROR unit.opensearch/0.juju-log Request GET to https://10.88.155.155:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.88.155.155:9200/_snapshot/s3-repository
unit-opensearch-1: 02:45:17 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:45:17 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:45:17 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:45:17 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:45:17 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:45:17 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:45:23 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:45:23 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:45:23 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:45:23 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:45:23 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:45:23 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:45:34 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:45:34 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:45:34 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:45:34 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:45:34 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:45:35 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:45:55 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:45:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:45:55 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:45:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:45:56 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:45:56 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:46:35 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:46:35 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:46:36 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:46:36 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:46:38 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:46:39 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:47:54 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:47:54 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:47:55 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:47:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:47:59 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:48:00 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:50:29 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:50:29 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:50:31 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:50:31 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:50:44 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:50:44 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:55:30 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:55:31 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:55:32 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:55:33 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:55:45 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:55:46 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:00:32 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:00:32 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:00:34 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:00:34 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:00:47 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:00:47 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:05:33 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:05:33 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:05:35 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:05:35 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:05:48 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:05:48 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:10:34 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:10:35 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:10:37 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:10:37 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:10:49 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:10:50 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:15:36 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:15:36 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:15:38 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:15:38 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:15:51 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:15:51 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:20:37 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:20:37 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:20:39 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:20:40 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:20:52 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:20:52 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:25:38 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:25:39 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:25:41 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:25:41 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:25:53 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:25:54 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:30:40 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:30:40 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:30:42 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:30:42 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:30:55 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:30:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:30:56 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:35:42 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:35:42 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:35:43 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:35:44 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:35:45 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:35:56 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:35:56 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...