[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.4    unsupported  03:07:09Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
opensearch                         active      3  opensearch                                 0  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
opensearch/0                 error     idle   0        10.93.147.211   9200/tcp  hook failed: "upgrade-charm"
opensearch/1*                error     idle   1        10.93.147.18    9200/tcp  hook failed: "upgrade-charm"
opensearch/2                 error     idle   2        10.93.147.128   9200/tcp  hook failed: "upgrade-charm"
self-signed-certificates/0*  active    idle   3        10.93.147.177             

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.93.147.211  juju-895eef-0  ubuntu@22.04      Running
1        started  10.93.147.18   juju-895eef-1  ubuntu@22.04      Running
2        started  10.93.147.128  juju-895eef-2  ubuntu@22.04      Running
3        started  10.93.147.177  juju-895eef-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-3: 01:57:52 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:57:52 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:57:52 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:57:57 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:57:57 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-1: 01:57:57 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:58:02 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:58:02 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-2: 01:58:02 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:58:02 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:58:02 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-0: 01:58:02 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-opensearch-2: 02:01:29 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:30 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:01:31 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:01:32 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:01:32 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:01:33 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:01:34 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:01:35 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:35 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:36 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:01:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:36 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:01:36 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:01:37 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:01:37 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:01:37 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:01:38 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:38 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:39 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:39 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:39 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:40 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:01:40 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:01:40 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:01:41 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:01:41 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:01:41 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:42 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:42 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:42 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:01:42 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:01:43 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:43 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:43 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:01:43 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:01:44 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:01:44 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:01:44 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:01:44 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:01:45 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:01:45 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:45 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:01:46 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:46 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:46 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:46 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:01:46 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:47 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:47 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:47 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:47 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:47 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:01:47 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:47 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:01:47 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:48 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:48 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:01:48 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:01:48 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:01:48 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:01:48 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:01:49 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:01:49 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:01:49 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:01:49 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:49 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:49 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:01:49 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:50 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:50 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:01:50 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:50 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:01:50 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:01:50 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:01:50 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:01:50 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:01:50 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:01:50 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:01:50 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:01:50 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:50 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:01:50 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:51 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:51 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:01:51 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:51 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:51 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:01:51 ERROR unit.opensearch/0.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:01:52 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:01:52 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:52 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:01:52 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:52 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:01:54 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:01:54 ERROR unit.opensearch/0.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:01:54 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:01:54 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:01:54 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:01:58 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:01:58 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:01:58 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:01:58 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:01:58 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:01:59 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:02:01 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:02:02 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:02:05 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:02:05 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:02:08 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:02:09 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:02:12 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:02:12 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:13 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:14 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:14 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:15 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:02:16 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:02:16 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:18 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:02:18 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:18 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:02:19 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:02:19 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:20 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:20 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:20 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:20 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:02:21 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:02:21 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:21 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:02:22 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:02:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:02:22 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:23 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:02:23 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:23 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:24 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:24 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:24 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:24 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:02:25 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:02:25 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:02:25 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:02:25 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:02:25 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:26 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:26 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:26 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:26 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:02:26 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:26 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:26 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:27 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:27 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:27 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:27 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:02:27 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:27 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:27 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:02:28 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:02:28 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:28 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:28 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:29 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:29 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:29 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:30 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:30 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:30 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:30 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:30 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:30 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:30 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:31 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:31 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:31 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:31 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:31 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:31 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:02:31 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:02:31 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:32 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:32 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:32 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:32 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:02:32 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:33 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:02:33 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:02:33 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:02:33 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:33 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:33 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:34 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:02:34 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:34 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:02:34 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:02:34 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:34 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:02:34 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:02:35 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:02:35 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:35 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:36 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:02:37 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:02:37 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:37 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:38 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:38 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:38 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:38 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:02:38 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:38 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:38 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:40 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:40 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:40 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:40 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:02:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:02:40 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:42 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:42 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:42 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:42 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:02:43 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:43 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:43 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:43 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:43 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:43 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:44 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:02:44 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:02:44 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:44 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:44 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:44 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:45 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:45 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:45 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:45 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:45 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:45 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:45 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:02:45 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:45 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:02:46 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:46 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:46 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:46 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:46 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:46 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:46 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:46 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:47 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:47 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:47 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:47 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:47 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:47 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:47 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:47 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:47 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:48 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:48 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:48 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:48 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:48 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:48 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:48 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:02:48 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:02:49 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:49 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:49 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:49 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:50 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:50 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:50 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:50 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:50 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:50 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:50 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:50 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:51 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:51 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:02:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:51 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:51 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:52 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:52 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Request GET to https://10.93.147.18:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/.charm_node_lock/_source/0
unit-opensearch-2: 02:02:52 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request GET to https://10.93.147.18:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:02:52 ERROR unit.opensearch/1.juju-log Request GET to https://10.93.147.18:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/.charm_node_lock/_source/0
unit-opensearch-0: 02:02:53 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Request GET to https://10.93.147.18:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/.charm_node_lock/_source/0
unit-opensearch-2: 02:02:53 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request GET to https://10.93.147.18:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:02:53 ERROR unit.opensearch/1.juju-log Request GET to https://10.93.147.18:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/.charm_node_lock/_source/0
unit-opensearch-0: 02:02:54 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:54 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:54 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:54 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:54 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request PUT to https://10.93.147.18:9200/.charm_node_lock?wait_for_active_shards=all with payload: {'settings': {'index': {'auto_expand_replicas': '0-all'}}} failed.(Attempts left: 2)
	Error: 400 Client Error: Bad Request for url: https://10.93.147.18:9200/.charm_node_lock?wait_for_active_shards=all
unit-opensearch-0: 02:02:54 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:54 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:54 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:54 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:54 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:55 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:55 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:02:55 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:02:55 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request PUT to https://10.93.147.18:9200/.charm_node_lock?wait_for_active_shards=all with payload: {'settings': {'index': {'auto_expand_replicas': '0-all'}}} failed.(Attempts left: 1)
	Error: 400 Client Error: Bad Request for url: https://10.93.147.18:9200/.charm_node_lock?wait_for_active_shards=all
unit-opensearch-2: 02:02:56 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:02:59 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:03:02 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:02 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:03 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:03:03 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:04 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:03:05 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:07 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:07 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:03:09 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:03:12 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:03:15 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:03:18 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:18 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:18 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:03:19 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:19 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:19 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:19 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:21 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:21 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:03:21 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:21 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:21 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:21 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:21 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:22 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:22 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:23 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:23 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:03:23 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:23 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:24 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:25 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:03:25 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:03:25 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:03:25 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:03:25 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:03:25 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:03:27 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:27 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:27 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:27 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:27 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:28 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:28 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:28 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:29 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:03:30 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:30 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:30 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:03:31 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:31 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:31 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:03:31 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:31 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:31 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:03:31 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:03:31 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:03:33 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:33 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:33 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:33 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:03:33 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:34 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:35 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:35 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:35 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:36 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:37 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:37 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:37 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:38 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:38 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:38 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:38 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:40 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:40 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:42 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:43 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:43 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:43 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:44 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:44 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:03:44 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:44 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:44 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:44 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:44 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:44 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:45 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:45 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:45 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:45 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:45 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:45 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:45 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:45 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:45 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:46 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:46 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:03:46 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:03:46 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:46 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:46 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:46 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:46 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:46 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:46 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request GET to https://10.93.147.211:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.93.147.211:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:03:46 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:03:46 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:47 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request GET to https://10.93.147.211:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.93.147.211:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:03:47 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:48 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:48 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:48 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:48 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:48 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:48 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:48 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:49 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request PUT to https://10.93.147.211:9200/.charm_node_lock?wait_for_active_shards=all with payload: {'settings': {'index': {'auto_expand_replicas': '0-all'}}} failed.(Attempts left: 2)
	Error: 400 Client Error: Bad Request for url: https://10.93.147.211:9200/.charm_node_lock?wait_for_active_shards=all
unit-opensearch-1: 02:03:49 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:03:49 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:03:49 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:03:50 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:03:50 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request PUT to https://10.93.147.211:9200/.charm_node_lock?wait_for_active_shards=all with payload: {'settings': {'index': {'auto_expand_replicas': '0-all'}}} failed.(Attempts left: 1)
	Error: 400 Client Error: Bad Request for url: https://10.93.147.211:9200/.charm_node_lock?wait_for_active_shards=all
unit-opensearch-1: 02:03:50 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:03:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:51 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:03:51 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:51 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:03:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:03:51 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:03:51 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:03:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:03:52 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:03:52 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:03:52 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:53 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:53 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:53 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:53 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:54 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:54 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:54 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:03:55 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:03:55 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:03:58 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:04:02 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:04:05 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:04:08 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:04:09 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:04:11 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:04:14 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:04:14 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:04:16 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:04:17 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:04:17 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:04:17 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:04:20 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:04:23 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:04:27 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:04:30 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:04:33 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:05:56 ERROR unit.opensearch/1.juju-log Request GET to https://10.93.147.18:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 5)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/_snapshot/s3-repository
unit-opensearch-1: 02:05:57 ERROR unit.opensearch/1.juju-log Request GET to https://10.93.147.18:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 4)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/_snapshot/s3-repository
unit-opensearch-1: 02:05:58 ERROR unit.opensearch/1.juju-log Request GET to https://10.93.147.18:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 3)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/_snapshot/s3-repository
unit-opensearch-1: 02:05:59 ERROR unit.opensearch/1.juju-log Request GET to https://10.93.147.18:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/_snapshot/s3-repository
unit-opensearch-1: 02:06:00 ERROR unit.opensearch/1.juju-log Request GET to https://10.93.147.18:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.93.147.18:9200/_snapshot/s3-repository
unit-opensearch-0: 02:06:37 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:06:37 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:06:38 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:06:38 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:06:38 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:06:38 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:06:44 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:06:44 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:06:44 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:06:44 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:06:44 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:06:44 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:06:55 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:06:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:06:55 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:06:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:06:56 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:06:56 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:07:16 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:07:16 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:07:17 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:07:17 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:07:17 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:07:17 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:07:56 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:07:56 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:07:56 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:07:57 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:07:59 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:08:00 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:09:16 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:09:16 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:09:18 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:09:18 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:09:24 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:09:24 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:11:52 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:11:52 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:12:03 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:12:03 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:12:08 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:12:09 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:16:53 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:16:53 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:17:04 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:17:04 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:17:10 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:17:10 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:21:54 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:21:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:22:05 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:22:06 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:22:11 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:22:11 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:26:56 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:26:56 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:27:07 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:27:07 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:27:13 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:27:13 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:31:57 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:31:57 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:32:08 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:32:08 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:32:14 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:32:14 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:36:59 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:36:59 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:37:09 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:37:10 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:37:15 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:37:15 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:42:00 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:42:00 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:42:11 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:42:11 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:42:16 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:42:17 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:47:01 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:47:02 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:47:12 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:47:12 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:47:18 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:47:18 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:52:03 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:52:03 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:52:13 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:52:13 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:52:19 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:52:19 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:57:04 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:57:04 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:57:14 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:57:15 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:57:20 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:57:21 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:02:05 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:02:05 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:02:16 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:02:16 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:02:22 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:02:22 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:07:07 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 546, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 429, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:07:07 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...