[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.78:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.78:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.78:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.78:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.153:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.78:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.49:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.153:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.78:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.78:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.78:9200/_nodes
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=228, count=229, last_expected_id=228)
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.253.205.78:9200/series_index/_search_shards
[32mINFO    [0m integration.ha.conftest:conftest.py:48 



The writes have been cleared.