[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  03:32:24Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
opensearch                         active      3  opensearch                                 0  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
opensearch/0                 error     idle   0        10.59.17.248    9200/tcp  hook failed: "upgrade-charm"
opensearch/1*                error     idle   1        10.59.17.11     9200/tcp  hook failed: "upgrade-charm"
opensearch/2                 error     idle   2        10.59.17.230    9200/tcp  hook failed: "upgrade-charm"
self-signed-certificates/0*  active    idle   3        10.59.17.226              

Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.59.17.248  juju-6523e6-0  ubuntu@22.04      Running
1        started  10.59.17.11   juju-6523e6-1  ubuntu@22.04      Running
2        started  10.59.17.230  juju-6523e6-2  ubuntu@22.04      Running
3        started  10.59.17.226  juju-6523e6-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-3: 02:26:30 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 02:26:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 02:26:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 02:26:33 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 02:26:33 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-1: 02:26:33 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 02:26:34 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 02:26:34 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-0: 02:26:34 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 02:26:38 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 02:26:38 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-2: 02:26:38 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-opensearch-0: 02:28:26 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:28:27 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:28:28 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:28:29 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:28:30 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:02 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:02 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:02 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:02 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:03 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:03 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:29:03 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:04 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:29:04 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:29:04 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:29:05 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:05 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:05 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:06 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:29:06 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:06 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:07 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:07 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:29:07 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:08 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:08 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:08 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:08 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:09 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:09 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:09 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:09 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:09 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:10 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:10 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:10 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:10 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:10 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:10 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:29:10 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:29:10 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:11 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:11 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:11 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:11 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:29:11 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:11 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:29:11 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:11 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:11 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:29:11 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:11 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:12 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:12 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:12 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:12 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:13 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:29:13 ERROR unit.opensearch/0.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:13 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:29:13 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:29:14 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:14 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:14 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:14 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:14 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:14 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:15 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:15 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:15 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:15 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:16 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:16 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:16 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:16 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:17 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:17 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:17 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:17 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:17 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:17 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:18 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:18 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:18 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:18 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:19 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:19 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:19 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:19 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:20 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:20 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:20 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:20 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:29:20 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:20 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:21 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:21 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:21 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:21 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:22 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:22 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:22 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:22 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:22 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:22 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:22 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:22 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:23 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:23 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:23 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:29:23 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:23 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:23 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:23 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:24 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:24 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:24 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:24 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:24 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:24 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:26 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:26 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:26 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:26 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:26 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:26 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:26 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:26 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:26 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:29:26 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:27 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:29:27 ERROR unit.opensearch/0.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:27 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:29:27 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:29:27 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:29:28 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:28 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:28 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:28 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:28 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:28 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:29 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:29 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:29 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:29 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:29 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:30 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:31 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:31 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:31 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:31 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:31 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:32 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:32 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:32 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:32 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:32 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:33 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:33 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:33 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:33 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:33 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:34 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:34 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:34 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:34 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:34 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:34 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:34 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:35 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:35 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:35 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:35 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:35 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:35 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:35 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:35 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:36 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:36 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:36 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:36 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:36 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:36 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:36 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:37 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:29:37 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:37 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:37 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:37 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:38 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:39 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:40 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:40 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:40 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:29:40 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:40 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:41 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:41 ERROR unit.opensearch/0.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:41 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:41 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:41 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:41 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:41 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:41 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:41 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:42 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:42 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:42 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:42 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:42 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:42 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:42 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:43 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:43 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:43 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:44 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:29:44 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:44 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:29:44 ERROR unit.opensearch/1.juju-log Request GET to https://10.59.17.11:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/.charm_node_lock/_source/0
unit-opensearch-2: 02:29:45 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:29:45 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:45 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:29:45 ERROR unit.opensearch/1.juju-log Request GET to https://10.59.17.11:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/.charm_node_lock/_source/0
unit-opensearch-2: 02:29:46 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:46 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:46 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:47 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:47 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:47 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:48 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:48 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:48 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:49 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:49 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:49 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:29:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:49 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Request GET to https://10.59.17.11:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/.charm_node_lock/_source/0
unit-opensearch-2: 02:29:50 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:50 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:50 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:29:51 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:29:51 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:51 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Request GET to https://10.59.17.11:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/.charm_node_lock/_source/0
unit-opensearch-2: 02:29:51 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:29:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:51 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:52 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:52 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:52 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:53 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:29:53 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:29:53 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:29:53 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:53 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:53 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:53 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:29:53 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:54 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:54 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:54 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:54 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:54 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:55 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:55 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:55 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:55 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:55 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:55 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:55 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:55 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:55 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:55 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:55 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:56 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:29:56 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:56 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:56 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:56 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:57 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:57 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:57 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:57 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:29:57 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:29:57 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:29:57 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:29:57 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:57 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:57 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:58 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:58 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:58 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:58 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:29:58 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:29:59 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:29:59 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:29:59 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:59 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:29:59 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:29:59 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:29:59 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:59 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:59 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:59 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:29:59 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:00 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:00 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:00 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:00 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:01 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:01 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:02 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:02 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:02 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:02 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:30:02 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:02 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:02 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:03 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:30:03 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:30:03 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:30:03 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:30:03 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:30:03 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:30:03 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:30:03 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:30:05 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:30:05 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:30:05 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:30:05 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:30:05 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:05 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:30:05 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:05 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:05 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:05 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:05 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:05 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:05 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:06 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:06 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:06 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:06 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:07 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:07 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:07 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:07 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:07 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:07 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:30:08 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:09 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:09 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:09 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:09 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:10 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:10 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:10 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:10 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:30:11 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:11 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:11 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:11 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:11 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:12 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:13 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:13 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:14 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:15 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:15 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:15 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:30:15 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:30:15 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:15 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:30:15 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:30:15 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:30:15 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:16 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:16 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:30:16 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:30:16 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:30:16 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:30:16 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:30:17 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:30:17 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:30:17 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:17 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:30:17 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:17 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:17 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:17 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:17 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request GET to https://10.59.17.11:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:30:18 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:30:18 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:18 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:30:18 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:18 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:19 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request GET to https://10.59.17.11:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:30:19 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:19 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:19 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:19 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:20 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:20 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:20 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:20 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:20 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request PUT to https://10.59.17.11:9200/.charm_node_lock?wait_for_active_shards=all with payload: {'settings': {'index': {'auto_expand_replicas': '0-all'}}} failed.(Attempts left: 2)
	Error: 400 Client Error: Bad Request for url: https://10.59.17.11:9200/.charm_node_lock?wait_for_active_shards=all
unit-opensearch-1: 02:30:20 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:21 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:21 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:30:21 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Request PUT to https://10.59.17.11:9200/.charm_node_lock?wait_for_active_shards=all with payload: {'settings': {'index': {'auto_expand_replicas': '0-all'}}} failed.(Attempts left: 1)
	Error: 400 Client Error: Bad Request for url: https://10.59.17.11:9200/.charm_node_lock?wait_for_active_shards=all
unit-opensearch-1: 02:30:21 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:30:21 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:30:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:22 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:22 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:22 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:30:22 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:23 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:23 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:23 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:30:23 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:23 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:30:24 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:24 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:24 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:24 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:25 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:25 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:26 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:26 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:30:26 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:26 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:26 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:26 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:27 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:28 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:28 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:28 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:28 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:28 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:29 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:29 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:30:29 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:30 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:30 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:30 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:31 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:31 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:31 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:31 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:30:31 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:30:32 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:32 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:33 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:33 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:33 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:33 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:34 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:34 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:35 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:30:35 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:30:35 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:30:35 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:30:38 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:31:53 ERROR unit.opensearch/1.juju-log Request GET to https://10.59.17.11:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 5)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/_snapshot/s3-repository
unit-opensearch-1: 02:31:54 ERROR unit.opensearch/1.juju-log Request GET to https://10.59.17.11:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 4)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/_snapshot/s3-repository
unit-opensearch-1: 02:31:55 ERROR unit.opensearch/1.juju-log Request GET to https://10.59.17.11:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 3)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/_snapshot/s3-repository
unit-opensearch-1: 02:31:56 ERROR unit.opensearch/1.juju-log Request GET to https://10.59.17.11:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/_snapshot/s3-repository
unit-opensearch-1: 02:31:57 ERROR unit.opensearch/1.juju-log Request GET to https://10.59.17.11:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.59.17.11:9200/_snapshot/s3-repository
unit-opensearch-1: 02:32:27 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:32:27 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:32:27 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:32:27 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:32:27 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:32:27 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:32:34 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:32:34 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:32:34 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:32:34 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:32:34 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:32:34 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:32:45 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:32:45 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:32:45 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:32:45 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:32:45 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:32:46 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:33:06 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:33:06 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:33:07 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:33:07 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:33:07 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:33:07 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:33:45 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:33:46 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:33:48 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:33:48 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:33:51 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:33:51 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:35:04 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:35:05 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:35:10 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:35:10 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:35:17 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:35:17 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:37:42 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:37:43 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:37:48 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:37:48 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:38:11 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:38:12 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:42:44 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:42:44 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:42:49 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:42:49 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:43:13 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:43:13 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:47:45 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:47:45 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:47:51 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:47:51 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:48:14 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:48:14 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:52:47 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:52:47 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:52:52 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:52:52 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:53:15 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:53:16 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:57:48 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:57:48 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:57:53 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:57:54 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:58:17 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:58:17 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:02:49 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:02:50 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:02:55 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:02:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:03:18 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:03:18 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:07:51 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:07:51 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:07:56 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:07:56 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:08:19 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:08:20 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:12:52 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:12:52 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:12:57 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:12:58 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:13:21 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:13:21 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:17:53 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:17:54 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:17:59 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:17:59 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:18:22 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:18:23 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:22:55 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:22:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:23:00 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:23:01 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:23:24 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:23:24 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:27:56 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:27:56 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:28:02 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:28:02 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:28:25 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:28:25 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...