[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.4    unsupported  03:43:59Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
opensearch                         active      3  opensearch                                 0  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
opensearch/0*                error     idle   0        10.137.118.74   9200/tcp  hook failed: "upgrade-charm"
opensearch/1                 error     idle   1        10.137.118.179  9200/tcp  hook failed: "upgrade-charm"
opensearch/2                 error     idle   2        10.137.118.140  9200/tcp  hook failed: "upgrade-charm"
self-signed-certificates/0*  active    idle   3        10.137.118.27             

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.137.118.74   juju-d8e884-0  ubuntu@22.04      Running
1        started  10.137.118.179  juju-d8e884-1  ubuntu@22.04      Running
2        started  10.137.118.140  juju-d8e884-2  ubuntu@22.04      Running
3        started  10.137.118.27   juju-d8e884-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-3: 02:38:23 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 02:38:23 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 02:38:24 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 02:38:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 02:38:29 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-0: 02:38:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 02:38:30 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 02:38:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-1: 02:38:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 02:38:41 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 02:38:41 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-2: 02:38:41 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-opensearch-2: 02:42:28 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:30 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:30 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:31 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:31 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:31 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:31 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:32 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:42:32 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:42:33 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:33 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:34 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:34 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:35 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:42:35 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:42:35 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:37 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:37 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:42:37 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:37 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:38 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:42:38 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:38 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:38 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:38 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:39 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:39 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:39 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:42:39 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:42:40 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:42:40 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:40 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:40 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:40 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:40 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:40 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:42:41 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:42:41 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:41 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:41 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:41 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:41 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:42:41 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:42 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:42 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:42 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:42 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:42 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:43 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:42:43 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:42:43 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:43 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:42:43 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:42:43 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:43 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:42:43 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:42:43 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:42:44 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:42:44 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:44 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:42:44 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:42:44 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:42:45 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:42:45 ERROR unit.opensearch/0.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:42:45 ERROR unit.opensearch/0.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:42:45 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:45 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:42:45 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:45 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:45 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:42:45 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:42:45 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:42:46 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:46 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:42:46 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:46 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:46 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:42:46 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:46 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:46 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:46 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:42:46 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:46 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:47 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:47 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:47 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:47 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:42:47 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:42:47 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:42:47 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:42:48 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:48 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:48 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:48 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:48 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:42:48 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:48 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:49 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:50 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:42:53 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:53 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:53 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:54 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:54 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:56 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:42:56 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:42:57 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:57 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:42:57 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:42:57 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:58 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:58 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:42:58 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:59 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:42:59 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:43:00 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:43:00 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:43:04 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:43:04 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:43:07 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:07 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:43:07 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:07 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:07 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:07 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:08 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:08 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:08 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:43:08 ERROR unit.opensearch/2.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:08 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:43:09 ERROR unit.opensearch/2.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:43:09 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:09 ERROR unit.opensearch/1.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:09 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:10 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:10 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:10 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:10 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:10 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:43:10 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:43:10 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:11 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:11 ERROR unit.opensearch/1.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:11 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:11 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:11 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:11 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:11 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:11 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:11 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:11 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:11 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:11 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:13 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:13 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:13 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:13 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:13 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:13 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:43:13 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:13 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:43:13 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:13 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:13 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:14 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:14 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:14 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:14 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:14 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:14 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:14 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:14 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:14 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:15 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:15 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:15 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:16 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:16 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:16 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:16 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:16 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:16 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:43:16 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:43:16 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:17 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:43:17 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:17 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:17 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:17 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:43:17 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:17 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:43:17 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:43:17 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:19 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-1: 02:43:19 ERROR unit.opensearch/1.juju-log certificates:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:43:19 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:19 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-0: 02:43:19 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:19 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:43:19 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:19 ERROR unit.opensearch/1.juju-log certificates:3: [Errno 111] Connection refused
unit-opensearch-2: 02:43:19 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:19 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:19 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:19 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:20 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:20 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:20 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:21 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:21 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:21 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:21 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:21 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:21 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:21 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:43:22 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:43:22 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:23 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:23 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:23 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:23 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:23 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:23 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:23 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:23 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:23 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:23 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:24 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:24 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:24 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:24 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:25 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:25 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:25 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:25 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:26 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:26 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:26 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:26 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:26 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:26 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:28 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:28 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:28 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:28 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:28 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:28 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:29 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:29 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:29 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:29 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:30 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:30 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:30 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:30 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:30 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:30 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:30 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:30 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:31 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:31 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:31 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:31 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:32 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:32 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:32 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:32 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:33 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:33 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:33 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:33 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:33 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:33 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:33 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:33 ERROR unit.opensearch/1.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:33 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:33 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:33 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:33 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:34 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:34 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:34 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:34 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:34 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:34 ERROR unit.opensearch/1.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:34 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:34 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:34 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:34 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:35 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:35 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:35 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:35 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:35 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:35 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:35 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:35 ERROR unit.opensearch/1.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:36 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:36 ERROR unit.opensearch/2.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:36 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:36 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:36 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-1: 02:43:36 ERROR unit.opensearch/1.juju-log [Errno 111] Connection refused
unit-opensearch-2: 02:43:37 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:37 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:37 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:37 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:37 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:37 ERROR unit.opensearch/1.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:37 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:37 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:38 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:38 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:38 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:38 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:38 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:38 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:38 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:43:38 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:43:38 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:38 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:38 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:38 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:39 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:39 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:39 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: Request GET to https://10.137.118.74:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.137.118.74:9200/.charm_node_lock/_source/0
unit-opensearch-0: 02:43:39 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Request GET to https://10.137.118.74:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.137.118.74:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:43:40 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: Request GET to https://10.137.118.74:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.137.118.74:9200/.charm_node_lock/_source/0
unit-opensearch-0: 02:43:40 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: Request GET to https://10.137.118.74:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.137.118.74:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:43:41 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:41 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:41 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:41 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:41 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:41 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:41 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:42 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:42 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:43:42 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:44 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:44 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:44 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:44 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:45 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:46 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:43:47 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:43:48 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:52 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:55 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:56 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:57 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:43:57 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:58 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:43:58 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:59 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:43:59 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:44:01 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:01 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:01 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:44:01 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:01 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:02 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:02 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:04 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:04 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:44:04 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:04 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:44:04 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:04 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:04 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:05 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:05 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:07 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:07 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:44:07 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:07 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:07 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:44:07 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:07 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:07 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:07 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:07 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:08 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:08 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:08 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:09 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:09 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:09 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:09 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:44:10 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:10 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:10 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:10 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:11 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:11 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:11 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:11 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:12 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:12 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:13 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:44:13 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:13 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:15 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:15 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:44:15 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:15 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:15 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:15 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:15 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:15 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:15 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:15 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:16 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:16 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:16 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:16 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-1: 02:44:16 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:17 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:18 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:18 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:20 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:21 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:21 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:22 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: Cannot connect to the OpenSearch server...
unit-opensearch-2: 02:44:22 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:44:22 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:44:22 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:23 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:44:23 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:23 ERROR unit.opensearch/2.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:44:23 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:44:23 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:44:23 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:44:23 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:44:23 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:24 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:44:24 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:24 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-1: 02:44:24 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:24 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Request GET to https://10.137.118.179:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.137.118.179:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:44:24 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:24 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:24 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:25 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Request GET to https://10.137.118.179:9200/.charm_node_lock/_source/0 with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.137.118.179:9200/.charm_node_lock/_source/0
unit-opensearch-1: 02:44:25 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:25 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:26 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:26 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:26 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:26 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-1: 02:44:26 ERROR unit.opensearch/1.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:26 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:26 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:26 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:27 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Request PUT to https://10.137.118.179:9200/.charm_node_lock?wait_for_active_shards=all with payload: {'settings': {'index': {'auto_expand_replicas': '0-all'}}} failed.(Attempts left: 2)
	Error: 400 Client Error: Bad Request for url: https://10.137.118.179:9200/.charm_node_lock?wait_for_active_shards=all
unit-opensearch-0: 02:44:27 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:27 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:27 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:27 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:28 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:28 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:28 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Request PUT to https://10.137.118.179:9200/.charm_node_lock?wait_for_active_shards=all with payload: {'settings': {'index': {'auto_expand_replicas': '0-all'}}} failed.(Attempts left: 1)
	Error: 400 Client Error: Bad Request for url: https://10.137.118.179:9200/.charm_node_lock?wait_for_active_shards=all
unit-opensearch-0: 02:44:28 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:28 ERROR unit.opensearch/0.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:29 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:29 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:29 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:29 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:29 ERROR unit.opensearch/2.juju-log opensearch-peers:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:44:29 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:30 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:30 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:30 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:31 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:31 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:31 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:33 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:36 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:39 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:39 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:42 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:43 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:45 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:46 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:44:49 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:49 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:50 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:52 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:52 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:53 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:53 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-2: 02:44:55 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:56 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:56 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:56 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:56 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:56 ERROR unit.opensearch/0.juju-log node-lock-fallback:0: [Errno 111] Connection refused
unit-opensearch-0: 02:44:58 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:58 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:44:58 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:44:58 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:59 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:44:59 ERROR unit.opensearch/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-2: 02:45:01 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:45:04 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-2: 02:45:07 ERROR unit.opensearch/2.juju-log opensearch-peers:1: [Errno 111] Connection refused
unit-opensearch-0: 02:46:27 ERROR unit.opensearch/0.juju-log Request GET to https://10.137.118.74:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 5)
	Error: 404 Client Error: Not Found for url: https://10.137.118.74:9200/_snapshot/s3-repository
unit-opensearch-0: 02:46:28 ERROR unit.opensearch/0.juju-log Request GET to https://10.137.118.74:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 4)
	Error: 404 Client Error: Not Found for url: https://10.137.118.74:9200/_snapshot/s3-repository
unit-opensearch-0: 02:46:29 ERROR unit.opensearch/0.juju-log Request GET to https://10.137.118.74:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 3)
	Error: 404 Client Error: Not Found for url: https://10.137.118.74:9200/_snapshot/s3-repository
unit-opensearch-0: 02:46:30 ERROR unit.opensearch/0.juju-log Request GET to https://10.137.118.74:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 2)
	Error: 404 Client Error: Not Found for url: https://10.137.118.74:9200/_snapshot/s3-repository
unit-opensearch-0: 02:46:31 ERROR unit.opensearch/0.juju-log Request GET to https://10.137.118.74:9200/_snapshot/s3-repository with payload: None failed.(Attempts left: 1)
	Error: 404 Client Error: Not Found for url: https://10.137.118.74:9200/_snapshot/s3-repository
unit-opensearch-1: 02:47:15 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:47:15 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:47:15 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:47:15 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:47:16 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:47:16 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:47:21 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:47:22 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:47:22 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:47:22 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:47:22 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:47:23 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:47:33 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:47:33 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:47:33 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:47:33 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:47:34 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:47:34 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:47:54 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:47:54 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:47:55 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:47:55 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:47:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:47:56 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:48:33 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:48:33 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:48:36 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:48:36 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:48:39 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:48:39 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:49:50 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:49:50 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:49:56 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:49:56 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:50:05 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:50:05 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:52:19 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:52:20 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:52:30 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:52:30 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:53:01 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:53:01 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 02:57:15 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 02:57:15 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 02:57:29 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 02:57:29 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 02:58:02 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 02:58:02 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:02:16 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:02:17 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:02:31 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:02:31 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:03:03 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:03:04 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:07:18 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:07:18 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:07:32 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:07:32 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:08:05 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:08:05 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:12:19 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:12:20 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:12:33 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:12:34 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:13:06 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:13:07 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:17:21 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:17:21 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:17:35 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:17:35 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:18:08 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:18:08 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:22:22 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:22:23 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:22:24 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:22:36 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:22:37 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:22:38 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:23:09 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:23:10 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:27:24 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:27:24 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:27:38 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:27:38 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:28:11 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:28:11 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:32:25 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:32:25 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:32:39 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:32:40 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:33:12 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:33:12 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:37:27 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:37:27 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:37:41 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:37:42 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:38:14 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:38:14 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-2: 03:42:28 ERROR unit.opensearch/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-2/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-2: 03:42:28 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-0: 03:42:43 ERROR unit.opensearch/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-0: 03:42:43 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-opensearch-1: 03:43:15 ERROR unit.opensearch/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 213, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/./src/charm.py", line 29, in __init__
    super().__init__(*args, distro=OpenSearchSnap)  # OpenSearchTarball
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 197, in __init__
    self.backup = backup(self)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_backups.py", line 1080, in backup
    if not charm.opensearch_peer_cm.deployment_desc():
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/opensearch_peer_clusters.py", line 358, in deployment_desc
    return DeploymentDescription.from_dict(current_deployment_desc)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 47, in from_dict
    return cls(**input_dict)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/opensearch/v0/models.py", line 32, in __init__
    super().__init__(**data)
  File "/var/lib/juju/agents/unit-opensearch-1/charm/venv/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DeploymentDescription
app
  value is not a valid dict (type=type_error.dict)
unit-opensearch-1: 03:43:15 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...